Request basic crud
havriutkin/team-code pull request #3
Opened 2024-03-01 17:10 UTC by OleksiiPliekhov

2024-03-01 17:36 UTC, havriutkin requested changes
We should reconsider PK in Request table

2024-03-01 17:36 UTC, havriutkin commented on src/main/java/com/shinobicoders/teamcodeapi/model/Request.java
> +        return Objects.equals(this.id, request.getId()) && this.status == request.getStatus()
It is enough to compare userID and ProjectID. Maybe we should change DB and have (userId, ProjectId) as PK

2024-03-01 17:36 UTC, havriutkin commented on src/main/java/com/shinobicoders/teamcodeapi/service/RequestService.java
> +        Optional<Request> existingRequest = requests.stream().filter(i -> i.getProject().equals(request.getProject())
After changing equals() method in Request class you can make it easier

2024-03-01 19:53 UTC, OleksiiPliekhov commented on src/main/java/com/shinobicoders/teamcodeapi/model/Request.java
> +        return Objects.equals(this.id, request.getId()) && this.status == request.getStatus()
Maybe we just should create a constraint of uniqueness Project-User pair in Request

2024-03-03 17:32 UTC, havriutkin requested changes

2024-03-03 17:32 UTC, havriutkin commented on src/main/java/com/shinobicoders/teamcodeapi/model/Request.java
> +        return this.getUser().equals(request.getUser())
Compare only Id

2024-03-03 17:32 UTC, havriutkin commented on src/main/java/com/shinobicoders/teamcodeapi/model/Request.java
> +    @ManyToOne
Add unique constraint on {user, project}

2024-03-03 17:32 UTC, havriutkin commented on src/main/java/com/shinobicoders/teamcodeapi/service/RequestService.java
> +
Add updateRequestStatus

2024-03-25 15:20 UTC, merged